default:
  dataconnection:
    driver: 
    server: 
    port: 
    database: 
    uid: 
    pwd: 
    
shinyapps:
  dataconnection:
    driver: 
    server: 
    port: 
    database: 
    uid: 
    pwd: 
    
local:
  dataconnection:
    driver: 'PostgresSQL35WL'
    server: 'localhost'
    port: 5432
    database: 'postgis'
    uid: 'postgres'
    pwd: ''

